# Generated by Django 5.2.7 on 2025-10-24 01:13

import random
import string

from django.db import migrations, models

length = 6
characters = string.ascii_uppercase + string.digits


def gen_code(apps, schema_editor):
    MyModel = apps.get_model("classroom", "classroom")
    for row in MyModel.objects.all():
        code = "".join(random.choice(characters) for _ in range(length))

        row.join_code = code
        row.save(update_fields=["join_code"])


class Migration(migrations.Migration):
    dependencies = [
        (
            "classroom",
            "0002_classroom_join_code_alter_classroom_allowed_students_and_more",
        ),
    ]

    operations = [migrations.RunPython(gen_code)]
