# Generated by Django 5.2.7 on 2025-10-27 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classroom", "0006_alter_classroom_active_requests"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="event_log",
            field=models.ManyToManyField(
                blank=True, related_name="event_log", to="classroom.request"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="active_request",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="active_student_request",
                to="classroom.request",
            ),
        ),
    ]
